CREATE TABLE IF NOT EXISTS cms_nav (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(20) NOT NULL,
    link VARCHAR(255) NOT NULL,
    position INTEGER NOT NULL,
    active BOOL NOT NULL
);

CREATE TABLE IF NOT EXISTS cms_page (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    permalink VARCHAR(100) NOT NULL UNIQUE,
    title VARCHAR(50) NOT NULL,
    imports TEXT NULL,
    content TEXT NOT NULL,
    pub_date DATETIME NOT NULL,
    active BOOL NOT NULL
);

CREATE TABLE IF NOT EXISTS cms_staticfile (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    filename VARCHAR(70) NOT NULL UNIQUE,
    file VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS cms_subnav (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(20) NOT NULL,
    link VARCHAR(255) NOT NULL,
    position INTEGER NOT NULL,
    active BOOL NOT NULL,
    nav_id INTEGER NOT NULL REFERENCES cms_nav(id) DEFERRABLE INITIALLY DEFERRED
);

INSERT OR IGNORE INTO django_migrations (app, name, applied) VALUES ('cms', '0001_initial', datetime('now'));
